version: '3.8'  # Docker Swarm 支持的 Compose 文件版本

services:
  spark-master:
    image: docker.io/bitnami/spark:latest
    hostname: master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'  # Spark Master Web UI
      - '7077:7077'  # Spark Master 服务端口
    deploy:
      placement:
        constraints:
          - node.role == manager  # 确保 Master 运行在 Swarm 管理节点
      resources:
        limits:
          cpus: '1'  # 为 Spark Master 分配 1 核 CPU
          memory: '2G'  # 分配 2G 内存

  spark-worker:
    image: docker.io/bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G  # 为 Worker 分配 2G 内存
      - SPARK_WORKER_CORES=1    # 每个 Worker 分配 1 核 CPU
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8081:8081'  # Spark Worker Web UI
    deploy:
      mode: replicated
      replicas: 3  # 设置3个 Worker 节点
      placement:
        constraints:
          - node.role == worker  # 确保 Worker 运行在 Swarm 的 Worker 节点
      resources:
        limits:
          cpus: '1'  # 为每个 Worker 分配 1 核 CPU
          memory: '2G'  # 为每个 Worker 分配 2G 内存

networks:
  spark-net:
    driver: overlay  # 使用 Swarm 的 overlay 网络
